"""Add Phase 4 models: Institution, Department, Course, UserProfile, CourseEnrollment

Revision ID: 476218e33db8
Revises: 5aac24be49e3
Create Date: 2026-07-06 15:20:18.904494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476218e33db8'
down_revision: Union[str, Sequence[str], None] = '5aac24be49e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('head_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_department_inst_code')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('lecturer_id', sa.String(length=36), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_course_inst_code')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_employee_id'), 'user_profiles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_student_id'), 'user_profiles', ['student_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLED', 'DROPPED', 'COMPLETED', 'SUSPENDED', name='enrollmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_course_student_enrollment')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_student_id'), 'course_enrollments', ['student_id'], unique=False)

    # Batch alter attendance_sessions for SQLite compatibility
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.alter_column('course_id',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=36),
                   existing_nullable=False)
        batch_op.create_foreign_key('fk_attendance_sessions_course', 'courses', ['course_id'], ['id'])

    # Batch alter users for SQLite compatibility
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=36),
                   existing_nullable=True)
        batch_op.create_foreign_key('fk_users_institution', 'institutions', ['institution_id'], ['id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('last_login')
        batch_op.drop_column('first_name')
        batch_op.drop_column('student_id')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('last_name')

    # Batch alter vouchers for SQLite compatibility
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=36),
                   existing_nullable=False)
        batch_op.create_foreign_key('fk_vouchers_institution', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vouchers_institution', type_='foreignkey')
        batch_op.alter_column('institution_id',
                   existing_type=sa.String(length=36),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=False)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_users_institution', type_='foreignkey')
        batch_op.alter_column('institution_id',
                   existing_type=sa.String(length=36),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=True)
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_sessions_course', type_='foreignkey')
        batch_op.alter_column('course_id',
                   existing_type=sa.String(length=36),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=False)
    op.drop_index(op.f('ix_course_enrollments_student_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_user_profiles_student_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_employee_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('courses')
    op.drop_table('departments')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
