"""Add missing user fields

Revision ID: 5aac24be49e3
Revises: 9aae6d78f85e
Create Date: 2026-07-06 15:06:12.413123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aac24be49e3'
down_revision: Union[str, Sequence[str], None] = '9aae6d78f85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
