"""Add mail_feedback_demo_tables

Revision ID: 99a8deaf3d90
Revises: a923d952b4de
Create Date: 2026-07-06 22:16:53.474832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a8deaf3d90'
down_revision: Union[str, Sequence[str], None] = 'a923d952b4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=150), nullable=True),
    sa.Column('institution_type', sa.String(length=80), nullable=True),
    sa.Column('institution_size', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_leads_email'), 'demo_leads', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_role', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('experience_rating', sa.Integer(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('allow_contact', sa.Boolean(), nullable=False),
    sa.Column('community_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('admin_viewed', sa.Boolean(), nullable=False),
    sa.Column('admin_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=200), nullable=True),
    sa.Column('moderation_action', sa.String(length=100), nullable=True),
    sa.Column('moderation_by', sa.String(length=36), nullable=True),
    sa.Column('moderation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.String(length=20), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('network_diagnostics', sa.JSON(), nullable=True),
    sa.Column('browser_info', sa.JSON(), nullable=True),
    sa.Column('sync_logs', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_category_status', 'feedback', ['category', 'status'], unique=False)
    op.create_index('idx_feedback_institution_category', 'feedback', ['institution', 'category'], unique=False)
    op.create_index('idx_feedback_severity_status', 'feedback', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_feedback_category'), 'feedback', ['category'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_institution'), 'feedback', ['institution'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('mail_smtp_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('rate_limit_per_sec', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mail_unsubscribes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_email_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_unsubscribes_recipient_email_hash'), 'mail_unsubscribes', ['recipient_email_hash'], unique=True)
    op.create_table('demo_onboarding_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('prefill_data', sa.JSON(), nullable=False),
    sa.Column('selected_timezone', sa.String(length=64), nullable=True),
    sa.Column('selected_date', sa.String(length=10), nullable=True),
    sa.Column('selected_time', sa.String(length=10), nullable=True),
    sa.Column('selected_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token', name='uq_onboarding_session_token')
    )
    op.create_index(op.f('ix_demo_onboarding_sessions_session_token'), 'demo_onboarding_sessions', ['session_token'], unique=True)
    op.create_table('escalation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('from_level', sa.String(length=20), nullable=False),
    sa.Column('to_level', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_history_feedback_id'), 'escalation_history', ['feedback_id'], unique=False)
    op.create_table('feedback_diagnostics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('network_latency_ms', sa.Float(), nullable=True),
    sa.Column('vpn_active', sa.Boolean(), nullable=False),
    sa.Column('offline_mode', sa.Boolean(), nullable=False),
    sa.Column('mqtt_sync_status', sa.String(length=30), nullable=True),
    sa.Column('mqtt_sync_logs', sa.JSON(), nullable=True),
    sa.Column('packet_loss_pct', sa.Float(), nullable=True),
    sa.Column('sync_duration_ms', sa.Float(), nullable=True),
    sa.Column('browser_version', sa.String(length=100), nullable=True),
    sa.Column('os_platform', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diag_feedback', 'feedback_diagnostics', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_diagnostics_feedback_id'), 'feedback_diagnostics', ['feedback_id'], unique=False)
    op.create_table('feedback_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reaction_feedback_user', 'feedback_reactions', ['feedback_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_feedback_reactions_feedback_id'), 'feedback_reactions', ['feedback_id'], unique=False)
    op.create_table('feedback_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_role', sa.String(length=30), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_replies_feedback_id'), 'feedback_replies', ['feedback_id'], unique=False)
    op.create_table('mail_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('smtp_profile_id', sa.String(length=36), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['smtp_profile_id'], ['mail_smtp_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index('idx_mail_template_category', 'mail_templates', ['category'], unique=False)
    op.create_index(op.f('ix_mail_templates_category'), 'mail_templates', ['category'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_feedback_id'), 'moderation_logs', ['feedback_id'], unique=False)
    op.create_table('demo_analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.String(length=36), nullable=True),
    sa.Column('onboarding_session_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('event_properties', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('institution_type', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.String(length=36), nullable=False),
    sa.Column('onboarding_session_id', sa.String(length=36), nullable=False),
    sa.Column('booking_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_timezone', sa.String(length=64), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('meeting_provider', sa.String(length=50), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_token', name='uq_demo_booking_token')
    )
    op.create_index(op.f('ix_demo_bookings_booking_token'), 'demo_bookings', ['booking_token'], unique=True)
    op.create_table('demo_trials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.String(length=36), nullable=False),
    sa.Column('onboarding_session_id', sa.String(length=36), nullable=False),
    sa.Column('trial_status', sa.String(length=30), nullable=False),
    sa.Column('trial_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('sandbox_data', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('smtp_profile_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('smtp_response', sa.Text(), nullable=True),
    sa.Column('tracking_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('template_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['smtp_profile_id'], ['mail_smtp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['mail_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index('idx_mail_queue_created', 'mail_queue', ['created_at'], unique=False)
    op.create_index('idx_mail_queue_status_next_retry', 'mail_queue', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_mail_queue_batch_id'), 'mail_queue', ['batch_id'], unique=False)
    op.create_index(op.f('ix_mail_queue_recipient_email'), 'mail_queue', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_mail_queue_status'), 'mail_queue', ['status'], unique=False)
    op.create_index(op.f('ix_mail_queue_template_type'), 'mail_queue', ['template_type'], unique=False)
    op.create_table('mail_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mail_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mail_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mail_audit_created', 'mail_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_mail_audit_mail_event', 'mail_audit_logs', ['mail_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_mail_audit_logs_event_type'), 'mail_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_mail_audit_logs_mail_id'), 'mail_audit_logs', ['mail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_audit_logs_mail_id'), table_name='mail_audit_logs')
    op.drop_index(op.f('ix_mail_audit_logs_event_type'), table_name='mail_audit_logs')
    op.drop_index('idx_mail_audit_mail_event', table_name='mail_audit_logs')
    op.drop_index('idx_mail_audit_created', table_name='mail_audit_logs')
    op.drop_table('mail_audit_logs')
    op.drop_index(op.f('ix_mail_queue_template_type'), table_name='mail_queue')
    op.drop_index(op.f('ix_mail_queue_status'), table_name='mail_queue')
    op.drop_index(op.f('ix_mail_queue_recipient_email'), table_name='mail_queue')
    op.drop_index(op.f('ix_mail_queue_batch_id'), table_name='mail_queue')
    op.drop_index('idx_mail_queue_status_next_retry', table_name='mail_queue')
    op.drop_index('idx_mail_queue_created', table_name='mail_queue')
    op.drop_table('mail_queue')
    op.drop_table('demo_trials')
    op.drop_index(op.f('ix_demo_bookings_booking_token'), table_name='demo_bookings')
    op.drop_table('demo_bookings')
    op.drop_table('demo_analytics_events')
    op.drop_index(op.f('ix_moderation_logs_feedback_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_mail_templates_category'), table_name='mail_templates')
    op.drop_index('idx_mail_template_category', table_name='mail_templates')
    op.drop_table('mail_templates')
    op.drop_index(op.f('ix_feedback_replies_feedback_id'), table_name='feedback_replies')
    op.drop_table('feedback_replies')
    op.drop_index(op.f('ix_feedback_reactions_feedback_id'), table_name='feedback_reactions')
    op.drop_index('idx_reaction_feedback_user', table_name='feedback_reactions')
    op.drop_table('feedback_reactions')
    op.drop_index(op.f('ix_feedback_diagnostics_feedback_id'), table_name='feedback_diagnostics')
    op.drop_index('idx_diag_feedback', table_name='feedback_diagnostics')
    op.drop_table('feedback_diagnostics')
    op.drop_index(op.f('ix_escalation_history_feedback_id'), table_name='escalation_history')
    op.drop_table('escalation_history')
    op.drop_index(op.f('ix_demo_onboarding_sessions_session_token'), table_name='demo_onboarding_sessions')
    op.drop_table('demo_onboarding_sessions')
    op.drop_index(op.f('ix_mail_unsubscribes_recipient_email_hash'), table_name='mail_unsubscribes')
    op.drop_table('mail_unsubscribes')
    op.drop_table('mail_smtp_profiles')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_institution'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_category'), table_name='feedback')
    op.drop_index('idx_feedback_severity_status', table_name='feedback')
    op.drop_index('idx_feedback_institution_category', table_name='feedback')
    op.drop_index('idx_feedback_category_status', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_demo_leads_email'), table_name='demo_leads')
    op.drop_table('demo_leads')
    # ### end Alembic commands ###
