"""Initial schema for PostgreSQL migration

Revision ID: 9aae6d78f85e
Revises: 
Create Date: 2026-07-06 14:53:08.327473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9aae6d78f85e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'INSTITUTIONAL_ADMIN', 'LECTURER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('lecturer_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_course_id'), 'attendance_sessions', ['course_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'INSTITUTIONAL_ADMIN', 'LECTURER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('email_binding', sa.String(length=255), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_vouchers_institution_id'), 'vouchers', ['institution_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'ABSENT', name='attendancestatus'), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_diagnostics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('network_latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('vpn_active', sa.BOOLEAN(), nullable=False),
    sa.Column('offline_mode', sa.BOOLEAN(), nullable=False),
    sa.Column('mqtt_sync_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('mqtt_sync_logs', sqlite.JSON(), nullable=True),
    sa.Column('packet_loss_pct', sa.FLOAT(), nullable=True),
    sa.Column('sync_duration_ms', sa.FLOAT(), nullable=True),
    sa.Column('browser_version', sa.VARCHAR(length=100), nullable=True),
    sa.Column('os_platform', sa.VARCHAR(length=100), nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_diagnostics_feedback_id'), 'feedback_diagnostics', ['feedback_id'], unique=False)
    op.create_index(op.f('idx_diag_feedback'), 'feedback_diagnostics', ['feedback_id'], unique=False)
    op.create_table('mail_templates',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('smtp_profile_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=40), nullable=False),
    sa.Column('subject_template', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body_template', sa.TEXT(), nullable=False),
    sa.Column('variables_schema', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['smtp_profile_id'], ['mail_smtp_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index(op.f('ix_mail_templates_category'), 'mail_templates', ['category'], unique=False)
    op.create_index(op.f('idx_mail_template_category'), 'mail_templates', ['category'], unique=False)
    op.create_table('demo_leads',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('institution_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('institution_size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role', sa.VARCHAR(length=40), nullable=True),
    sa.Column('country', sa.VARCHAR(length=2), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_leads_email'), 'demo_leads', ['email'], unique=1)
    op.create_table('mail_audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('mail_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mail_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_audit_logs_mail_id'), 'mail_audit_logs', ['mail_id'], unique=False)
    op.create_index(op.f('ix_mail_audit_logs_event_type'), 'mail_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_mail_audit_mail_event'), 'mail_audit_logs', ['mail_id', 'event_type'], unique=False)
    op.create_index(op.f('idx_mail_audit_created'), 'mail_audit_logs', ['created_at'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('admin_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_feedback_id'), 'moderation_logs', ['feedback_id'], unique=False)
    op.create_table('mail_unsubscribes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('recipient_email_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_unsubscribes_recipient_email_hash'), 'mail_unsubscribes', ['recipient_email_hash'], unique=1)
    op.create_table('demo_bookings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('onboarding_session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('booking_token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('scheduled_at_utc', sa.DATETIME(), nullable=True),
    sa.Column('scheduled_timezone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('meeting_url', sa.TEXT(), nullable=True),
    sa.Column('meeting_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reminder_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('rescheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_token', name=op.f('uq_demo_booking_token'))
    )
    op.create_index(op.f('ix_demo_bookings_booking_token'), 'demo_bookings', ['booking_token'], unique=1)
    op.create_table('mail_smtp_profiles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('use_tls', sa.BOOLEAN(), nullable=False),
    sa.Column('from_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rate_limit_per_sec', sa.INTEGER(), nullable=False),
    sa.Column('daily_quota', sa.INTEGER(), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('demo_onboarding_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=30), nullable=False),
    sa.Column('progress', sqlite.JSON(), nullable=False),
    sa.Column('prefill_data', sqlite.JSON(), nullable=False),
    sa.Column('selected_timezone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('selected_date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('selected_time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('selected_datetime_utc', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity_at', sa.DATETIME(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token', name=op.f('uq_onboarding_session_token'))
    )
    op.create_index(op.f('ix_demo_onboarding_sessions_session_token'), 'demo_onboarding_sessions', ['session_token'], unique=1)
    op.create_table('demo_trials',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('onboarding_session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('trial_status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('trial_start_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_end_at', sa.DATETIME(), nullable=True),
    sa.Column('expired_at', sa.DATETIME(), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=False),
    sa.Column('sandbox_data', sqlite.JSON(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_queue',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('smtp_profile_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('recipient_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body_html', sa.TEXT(), nullable=False),
    sa.Column('body_text', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.Column('next_retry_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('smtp_response', sa.TEXT(), nullable=True),
    sa.Column('tracking_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('template_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['smtp_profile_id'], ['mail_smtp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['mail_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index(op.f('ix_mail_queue_template_type'), 'mail_queue', ['template_type'], unique=False)
    op.create_index(op.f('ix_mail_queue_status'), 'mail_queue', ['status'], unique=False)
    op.create_index(op.f('ix_mail_queue_recipient_email'), 'mail_queue', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_mail_queue_batch_id'), 'mail_queue', ['batch_id'], unique=False)
    op.create_index(op.f('idx_mail_queue_status_next_retry'), 'mail_queue', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_mail_queue_created'), 'mail_queue', ['created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=30), nullable=False),
    sa.Column('institution', sa.VARCHAR(length=150), nullable=True),
    sa.Column('category', sa.VARCHAR(length=40), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('experience_rating', sa.INTEGER(), nullable=True),
    sa.Column('screenshot_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('allow_contact', sa.BOOLEAN(), nullable=False),
    sa.Column('community_visible', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('upvotes', sa.INTEGER(), nullable=False),
    sa.Column('reply_count', sa.INTEGER(), nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('admin_viewed', sa.BOOLEAN(), nullable=False),
    sa.Column('admin_viewed_at', sa.DATETIME(), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), nullable=False),
    sa.Column('is_hidden', sa.BOOLEAN(), nullable=False),
    sa.Column('flag_reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('moderation_action', sa.VARCHAR(length=100), nullable=True),
    sa.Column('moderation_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('moderation_at', sa.DATETIME(), nullable=True),
    sa.Column('escalation_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('escalation_count', sa.INTEGER(), nullable=False),
    sa.Column('device_info', sqlite.JSON(), nullable=True),
    sa.Column('network_diagnostics', sqlite.JSON(), nullable=True),
    sa.Column('browser_info', sqlite.JSON(), nullable=True),
    sa.Column('sync_logs', sqlite.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=20), nullable=True),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_institution'), 'feedback', ['institution'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_category'), 'feedback', ['category'], unique=False)
    op.create_index(op.f('idx_feedback_severity_status'), 'feedback', ['severity', 'status'], unique=False)
    op.create_index(op.f('idx_feedback_institution_category'), 'feedback', ['institution', 'category'], unique=False)
    op.create_index(op.f('idx_feedback_category_status'), 'feedback', ['category', 'status'], unique=False)
    op.create_table('escalation_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('from_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('to_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_history_feedback_id'), 'escalation_history', ['feedback_id'], unique=False)
    op.create_table('feedback_reactions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_reactions_feedback_id'), 'feedback_reactions', ['feedback_id'], unique=False)
    op.create_index(op.f('idx_reaction_feedback_user'), 'feedback_reactions', ['feedback_id', 'user_id'], unique=1)
    op.create_table('feedback_replies',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=30), nullable=False),
    sa.Column('is_anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_replies_feedback_id'), 'feedback_replies', ['feedback_id'], unique=False)
    op.create_table('demo_analytics_events',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('demo_lead_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('onboarding_session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('event_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('event_properties', sqlite.JSON(), nullable=False),
    sa.Column('country', sa.VARCHAR(length=2), nullable=True),
    sa.Column('institution_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['demo_lead_id'], ['demo_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['demo_onboarding_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
